In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
flattened = reshaped.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flattened = reshaped.flatten()
flattened[0] = 99
flattened

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
flattened = reshaped.flatten()
flattened[0:3] = [99, 77, 88]
flattened

array([99, 77, 88,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
flattened

array([99, 77, 88,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
raveled = reshaped.ravel()
raveled[1] = 77
raveled

array([ 1, 77,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
raveled

array([ 1, 77,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
reshaped

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [16]:
arr1+arr2

array([3, 5, 7])

In [17]:
arr1 + 4

array([5, 6, 7])

In [18]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([[2],[4],[6]])
print(arr2)


[1 2 3]
[[2]
 [4]
 [6]]


In [19]:
arr1 + arr2

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])