In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow version:{}".format(tf.__version__))

TensorFlow version:2.18.0


In [5]:
d0=tf.constant(1)

In [6]:
print("Dimension is", tf.rank(d0).numpy())

Dimension is 0


In [7]:
print(d0)

tf.Tensor(1, shape=(), dtype=int32)


In [10]:
d1=tf.ones((2,))
print("Dimension is",tf.rank(d1).numpy())
print(d1)

Dimension is 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [11]:
d2=tf.ones((2,2))
print("Dimension is",tf.rank(d2).numpy())
print(d2)

Dimension is 2
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [12]:
d3=tf.ones((2,2,2))
print("Dimension is",tf.rank(d3).numpy())
print(d3)

Dimension is 3
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [17]:
x1 = tf.Variable(23)
x2 = tf.Variable([[[0.,1.,2],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
x0 = 123
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [19]:
x1.assign(100)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [20]:
x1 = tf.Variable(100)
print(x1)
x1.assign(200)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>

In [21]:
x2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [22]:
x0

123

Reshape

In [24]:
x112 = tf.reshape(x2,[1,12]) #12 row 1 columns
x112

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

Declaring variable with type

In [25]:
xf64 = tf.Variable(202, dtype=tf.float64)
xf64.dtype

tf.float64

In [26]:
xf64.numpy()

np.float64(202.0)

Ranking check dimensions variable

In [27]:
tf.rank(xf64)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [28]:
tf.rank(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [29]:
t = tf.constant([[[1,1,1],[2,2,2]],[[4,3,5],[4,4,414]]])
tf.rank(t).numpy()

np.int32(3)

In [30]:
t.numpy()

array([[[  1,   1,   1],
        [  2,   2,   2]],

       [[  4,   3,   5],
        [  4,   4, 414]]], dtype=int32)

Tensor Slicing

In [31]:
tensor3 = t[1,1,2] #Slice 1, row0, column 2
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=414>

In [33]:
x = tf.constant([0,1,1,2,3,4,8,13,21,34])
print("Before 4:" , x[:4].numpy())
print("After 4:" , x[:4].numpy())
print("From 2, before 7:", x[2:7].numpy())
print("Every other item:", x[::2].numpy())
print("Reversed:", x[::-1].numpy())

Before 4: [0 1 1 2]
After 4: [0 1 1 2]
From 2, before 7: [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


Casting tensor to a datatype

In [34]:
a = tf.constant([[1,2],[3,4]])
i = tf.cast(a,dtype=tf.float32)
print(a)
print(i)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


Tensor Operation

In [35]:
a= tf.constant([[1,2],[3,4]])
b= tf.constant([[5,6],[7,8]])
c = a +b
a.numpy()
b.numpy()
print(a)
print(b)
print("\n output of c",c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

 output of c tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [36]:
d =tf.square(c)
print(d)

tf.Tensor(
[[ 36  64]
 [100 144]], shape=(2, 2), dtype=int32)


In [37]:
tf.add(a,b)
tf.subtract(b,a)
e= a*b

In [38]:
print(6)
tf.multiply(a,b) # No of columns in a == No o

6


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>